// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/garguelles/archpass/ent/attendee"
	"github.com/garguelles/archpass/ent/event"
	"github.com/garguelles/archpass/ent/user"
)

// AttendeeCreate is the builder for creating a Attendee entity.
type AttendeeCreate struct {
	config
	mutation *AttendeeMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (ac *AttendeeCreate) SetUserID(i int) *AttendeeCreate {
	ac.mutation.SetUserID(i)
	return ac
}

// SetEventID sets the "event_id" field.
func (ac *AttendeeCreate) SetEventID(i int) *AttendeeCreate {
	ac.mutation.SetEventID(i)
	return ac
}

// SetTicketID sets the "ticket_id" field.
func (ac *AttendeeCreate) SetTicketID(i int) *AttendeeCreate {
	ac.mutation.SetTicketID(i)
	return ac
}

// SetEventsID sets the "events" edge to the Event entity by ID.
func (ac *AttendeeCreate) SetEventsID(id int) *AttendeeCreate {
	ac.mutation.SetEventsID(id)
	return ac
}

// SetEvents sets the "events" edge to the Event entity.
func (ac *AttendeeCreate) SetEvents(e *Event) *AttendeeCreate {
	return ac.SetEventsID(e.ID)
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (ac *AttendeeCreate) SetUsersID(id int) *AttendeeCreate {
	ac.mutation.SetUsersID(id)
	return ac
}

// SetUsers sets the "users" edge to the User entity.
func (ac *AttendeeCreate) SetUsers(u *User) *AttendeeCreate {
	return ac.SetUsersID(u.ID)
}

// Mutation returns the AttendeeMutation object of the builder.
func (ac *AttendeeCreate) Mutation() *AttendeeMutation {
	return ac.mutation
}

// Save creates the Attendee in the database.
func (ac *AttendeeCreate) Save(ctx context.Context) (*Attendee, error) {
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AttendeeCreate) SaveX(ctx context.Context) *Attendee {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AttendeeCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AttendeeCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AttendeeCreate) check() error {
	if _, ok := ac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Attendee.user_id"`)}
	}
	if _, ok := ac.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "Attendee.event_id"`)}
	}
	if _, ok := ac.mutation.TicketID(); !ok {
		return &ValidationError{Name: "ticket_id", err: errors.New(`ent: missing required field "Attendee.ticket_id"`)}
	}
	if len(ac.mutation.EventsIDs()) == 0 {
		return &ValidationError{Name: "events", err: errors.New(`ent: missing required edge "Attendee.events"`)}
	}
	if len(ac.mutation.UsersIDs()) == 0 {
		return &ValidationError{Name: "users", err: errors.New(`ent: missing required edge "Attendee.users"`)}
	}
	return nil
}

func (ac *AttendeeCreate) sqlSave(ctx context.Context) (*Attendee, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AttendeeCreate) createSpec() (*Attendee, *sqlgraph.CreateSpec) {
	var (
		_node = &Attendee{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(attendee.Table, sqlgraph.NewFieldSpec(attendee.FieldID, field.TypeInt))
	)
	if value, ok := ac.mutation.TicketID(); ok {
		_spec.SetField(attendee.FieldTicketID, field.TypeInt, value)
		_node.TicketID = value
	}
	if nodes := ac.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attendee.EventsTable,
			Columns: []string{attendee.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EventID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attendee.UsersTable,
			Columns: []string{attendee.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AttendeeCreateBulk is the builder for creating many Attendee entities in bulk.
type AttendeeCreateBulk struct {
	config
	err      error
	builders []*AttendeeCreate
}

// Save creates the Attendee entities in the database.
func (acb *AttendeeCreateBulk) Save(ctx context.Context) ([]*Attendee, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Attendee, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AttendeeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AttendeeCreateBulk) SaveX(ctx context.Context) []*Attendee {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AttendeeCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AttendeeCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
