// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/garguelles/archpass/ent/event"
	"github.com/garguelles/archpass/ent/ticket"
)

// TicketCreate is the builder for creating a Ticket entity.
type TicketCreate struct {
	config
	mutation *TicketMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (tc *TicketCreate) SetName(s string) *TicketCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetDescription sets the "description" field.
func (tc *TicketCreate) SetDescription(s string) *TicketCreate {
	tc.mutation.SetDescription(s)
	return tc
}

// SetTicketSlug sets the "ticket_slug" field.
func (tc *TicketCreate) SetTicketSlug(s string) *TicketCreate {
	tc.mutation.SetTicketSlug(s)
	return tc
}

// SetMintPrice sets the "mint_price" field.
func (tc *TicketCreate) SetMintPrice(s string) *TicketCreate {
	tc.mutation.SetMintPrice(s)
	return tc
}

// SetQuantity sets the "quantity" field.
func (tc *TicketCreate) SetQuantity(i int) *TicketCreate {
	tc.mutation.SetQuantity(i)
	return tc
}

// SetEventID sets the "event_id" field.
func (tc *TicketCreate) SetEventID(i int) *TicketCreate {
	tc.mutation.SetEventID(i)
	return tc
}

// SetContractAddress sets the "contract_address" field.
func (tc *TicketCreate) SetContractAddress(s string) *TicketCreate {
	tc.mutation.SetContractAddress(s)
	return tc
}

// SetNillableContractAddress sets the "contract_address" field if the given value is not nil.
func (tc *TicketCreate) SetNillableContractAddress(s *string) *TicketCreate {
	if s != nil {
		tc.SetContractAddress(*s)
	}
	return tc
}

// SetTransactionHash sets the "transaction_hash" field.
func (tc *TicketCreate) SetTransactionHash(s string) *TicketCreate {
	tc.mutation.SetTransactionHash(s)
	return tc
}

// SetNillableTransactionHash sets the "transaction_hash" field if the given value is not nil.
func (tc *TicketCreate) SetNillableTransactionHash(s *string) *TicketCreate {
	if s != nil {
		tc.SetTransactionHash(*s)
	}
	return tc
}

// SetBlockNumber sets the "block_number" field.
func (tc *TicketCreate) SetBlockNumber(s string) *TicketCreate {
	tc.mutation.SetBlockNumber(s)
	return tc
}

// SetNillableBlockNumber sets the "block_number" field if the given value is not nil.
func (tc *TicketCreate) SetNillableBlockNumber(s *string) *TicketCreate {
	if s != nil {
		tc.SetBlockNumber(*s)
	}
	return tc
}

// SetCreatedAt sets the "created_at" field.
func (tc *TicketCreate) SetCreatedAt(t time.Time) *TicketCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TicketCreate) SetNillableCreatedAt(t *time.Time) *TicketCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *TicketCreate) SetUpdatedAt(t time.Time) *TicketCreate {
	tc.mutation.SetUpdatedAt(t)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *TicketCreate) SetNillableUpdatedAt(t *time.Time) *TicketCreate {
	if t != nil {
		tc.SetUpdatedAt(*t)
	}
	return tc
}

// SetEventsID sets the "events" edge to the Event entity by ID.
func (tc *TicketCreate) SetEventsID(id int) *TicketCreate {
	tc.mutation.SetEventsID(id)
	return tc
}

// SetEvents sets the "events" edge to the Event entity.
func (tc *TicketCreate) SetEvents(e *Event) *TicketCreate {
	return tc.SetEventsID(e.ID)
}

// Mutation returns the TicketMutation object of the builder.
func (tc *TicketCreate) Mutation() *TicketMutation {
	return tc.mutation
}

// Save creates the Ticket in the database.
func (tc *TicketCreate) Save(ctx context.Context) (*Ticket, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TicketCreate) SaveX(ctx context.Context) *Ticket {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TicketCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TicketCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TicketCreate) defaults() {
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := ticket.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		v := ticket.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TicketCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Ticket.name"`)}
	}
	if _, ok := tc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Ticket.description"`)}
	}
	if _, ok := tc.mutation.TicketSlug(); !ok {
		return &ValidationError{Name: "ticket_slug", err: errors.New(`ent: missing required field "Ticket.ticket_slug"`)}
	}
	if v, ok := tc.mutation.TicketSlug(); ok {
		if err := ticket.TicketSlugValidator(v); err != nil {
			return &ValidationError{Name: "ticket_slug", err: fmt.Errorf(`ent: validator failed for field "Ticket.ticket_slug": %w`, err)}
		}
	}
	if _, ok := tc.mutation.MintPrice(); !ok {
		return &ValidationError{Name: "mint_price", err: errors.New(`ent: missing required field "Ticket.mint_price"`)}
	}
	if _, ok := tc.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Ticket.quantity"`)}
	}
	if _, ok := tc.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "Ticket.event_id"`)}
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Ticket.created_at"`)}
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Ticket.updated_at"`)}
	}
	if len(tc.mutation.EventsIDs()) == 0 {
		return &ValidationError{Name: "events", err: errors.New(`ent: missing required edge "Ticket.events"`)}
	}
	return nil
}

func (tc *TicketCreate) sqlSave(ctx context.Context) (*Ticket, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TicketCreate) createSpec() (*Ticket, *sqlgraph.CreateSpec) {
	var (
		_node = &Ticket{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(ticket.Table, sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(ticket.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.Description(); ok {
		_spec.SetField(ticket.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := tc.mutation.TicketSlug(); ok {
		_spec.SetField(ticket.FieldTicketSlug, field.TypeString, value)
		_node.TicketSlug = value
	}
	if value, ok := tc.mutation.MintPrice(); ok {
		_spec.SetField(ticket.FieldMintPrice, field.TypeString, value)
		_node.MintPrice = value
	}
	if value, ok := tc.mutation.Quantity(); ok {
		_spec.SetField(ticket.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if value, ok := tc.mutation.ContractAddress(); ok {
		_spec.SetField(ticket.FieldContractAddress, field.TypeString, value)
		_node.ContractAddress = value
	}
	if value, ok := tc.mutation.TransactionHash(); ok {
		_spec.SetField(ticket.FieldTransactionHash, field.TypeString, value)
		_node.TransactionHash = value
	}
	if value, ok := tc.mutation.BlockNumber(); ok {
		_spec.SetField(ticket.FieldBlockNumber, field.TypeString, value)
		_node.BlockNumber = value
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.SetField(ticket.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.SetField(ticket.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := tc.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.EventsTable,
			Columns: []string{ticket.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EventID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TicketCreateBulk is the builder for creating many Ticket entities in bulk.
type TicketCreateBulk struct {
	config
	err      error
	builders []*TicketCreate
}

// Save creates the Ticket entities in the database.
func (tcb *TicketCreateBulk) Save(ctx context.Context) ([]*Ticket, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Ticket, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TicketCreateBulk) SaveX(ctx context.Context) []*Ticket {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TicketCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TicketCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
